apiVersion: apps/v1
kind: Deployment
metadata: 
    name: mavenwebapp
    namespace: eswar-ns
spec:
    replicas: 3
    selector:
      matchLabels:
        app: mavenwebapp
    template:
      metadata:
         name: mavenwebapppod
         labels:
            app: mavenwebapp
      spec:
         containers:
         - name: mavenwebapp
           image: entertainmentt/maven-web-application:1
           ports:
           - containerPort: 8080
           resources:
             requests:
                 cpu: 100m
                 memory: 256Mi
             limits:
                 cpu: 300m
                 memory: 512Mi
---
apiVersion: v1
kind: Service
metadata: 
    name: mavenwebappsvc
    namespace: eswar-ns
    labels:
        name: mavenwebapp
spec:
    ports:
    - port: 8080
      targetPort: 8080
    selector:
      app: mavenwebapp
      type: NodePort
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
    name: mavenwebapphpa
    namespace: eswar-ns
spec:
    scaleTargetRef:
       apiVersion: apps/v1
       kind: Deployment
       name: mavenwebapp
    minReplicas: 2
    maxReplicas: 5
    metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 85
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 90
