apiVersion: apps/v1
kind: ReplicaSet
metadata: 
    name: pythonapp
    namespace: eswar-ns
    labels:
      app: pythonapp
spec:
    replicas: 1
    selector:
      matchLabels:
         app: pythonapp
    template:
      metadata:
         labels:
           app: pythonapp
      spec:
        containers:
        - name: python
          image: entertainmentt/python-life:1
          ports:
          - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata: 
    name: pythonappsvc
    namespace: eswar-ns
spec:
    type: NodePort
    selector:
        app: pythonapp
    ports:
    - port: 5000
      targetPort: 5000
